services:
  db:
    image: mysql:8.0
    container_name: todo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  django:
    build: .
    container_name: todo_container
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: >
      sh -c "
        echo 'Waiting for MySQL...' &&
        while ! nc -z db 3306; do
          echo 'MySQL is unavailable - sleeping' &&
          sleep 1
        done &&
        echo 'MySQL is ready' &&
        echo 'Starting Django server' &&
        gunicorn todo_list_be.wsgi:application --bind 0.0.0.0:8000
      "

volumes:
  mysql_data: